# Generated by Django 6.0.5 on 2026-06-08 05:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=accounts.models.generate_api_key),
        ),
    ]
