# Generated by Django 6.0.5 on 2026-06-08 06:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=accounts.models.generate_api_key, max_length=100, unique=True),
        ),
    ]
