# Generated by Django 6.0.5 on 2026-06-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
