# Generated by Django 6.0.5 on 2026-06-19 11:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=accounts.models.generate_api_key, unique=True),
        ),
    ]
