# Generated by Django 6.0.5 on 2026-06-22 08:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.TextField(default=accounts.models.generate_api_key, unique=True),
        ),
    ]
