# Generated by Django 6.0.5 on 2026-06-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasksubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
