# Generated by Django 6.0.5 on 2026-06-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_file/'),
        ),
    ]
