# Generated by Django 6.0.5 on 2026-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_submission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='submission_file',
        ),
        migrations.AddField(
            model_name='task',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
